//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisPolicy) DeepCopyInto(out *DiagnosisPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisPolicy.
func (in *DiagnosisPolicy) DeepCopy() *DiagnosisPolicy {
	if in == nil {
		return nil
	}
	out := new(DiagnosisPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiagnosisPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisPolicyList) DeepCopyInto(out *DiagnosisPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DiagnosisPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisPolicyList.
func (in *DiagnosisPolicyList) DeepCopy() *DiagnosisPolicyList {
	if in == nil {
		return nil
	}
	out := new(DiagnosisPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiagnosisPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisPolicySpec) DeepCopyInto(out *DiagnosisPolicySpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EventReasons != nil {
		in, out := &in.EventReasons, &out.EventReasons
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxIterations != nil {
		in, out := &in.MaxIterations, &out.MaxIterations
		*out = new(int32)
		**out = **in
	}
	if in.Redact != nil {
		in, out := &in.Redact, &out.Redact
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisPolicySpec.
func (in *DiagnosisPolicySpec) DeepCopy() *DiagnosisPolicySpec {
	if in == nil {
		return nil
	}
	out := new(DiagnosisPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisPolicyStatus) DeepCopyInto(out *DiagnosisPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisPolicyStatus.
func (in *DiagnosisPolicyStatus) DeepCopy() *DiagnosisPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(DiagnosisPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KscribeDiagnosis) DeepCopyInto(out *KscribeDiagnosis) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KscribeDiagnosis.
func (in *KscribeDiagnosis) DeepCopy() *KscribeDiagnosis {
	if in == nil {
		return nil
	}
	out := new(KscribeDiagnosis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KscribeDiagnosis) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KscribeDiagnosisList) DeepCopyInto(out *KscribeDiagnosisList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KscribeDiagnosis, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KscribeDiagnosisList.
func (in *KscribeDiagnosisList) DeepCopy() *KscribeDiagnosisList {
	if in == nil {
		return nil
	}
	out := new(KscribeDiagnosisList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KscribeDiagnosisList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KscribeDiagnosisSpec) DeepCopyInto(out *KscribeDiagnosisSpec) {
	*out = *in
	if in.FirstTimestamp != nil {
		in, out := &in.FirstTimestamp, &out.FirstTimestamp
		*out = (*in).DeepCopy()
	}
	if in.LastTimestamp != nil {
		in, out := &in.LastTimestamp, &out.LastTimestamp
		*out = (*in).DeepCopy()
	}
	if in.MaxIterations != nil {
		in, out := &in.MaxIterations, &out.MaxIterations
		*out = new(int32)
		**out = **in
	}
	if in.Redact != nil {
		in, out := &in.Redact, &out.Redact
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KscribeDiagnosisSpec.
func (in *KscribeDiagnosisSpec) DeepCopy() *KscribeDiagnosisSpec {
	if in == nil {
		return nil
	}
	out := new(KscribeDiagnosisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KscribeDiagnosisStatus) DeepCopyInto(out *KscribeDiagnosisStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KscribeDiagnosisStatus.
func (in *KscribeDiagnosisStatus) DeepCopy() *KscribeDiagnosisStatus {
	if in == nil {
		return nil
	}
	out := new(KscribeDiagnosisStatus)
	in.DeepCopyInto(out)
	return out
}
