---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kscribe-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kscribe.amjadjibon.dev
  resources:
  - diagnosispolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kscribe.amjadjibon.dev
  resources:
  - kscribediagnoses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kscribe.amjadjibon.dev
  resources:
  - kscribediagnoses/status
  verbs:
  - get
  - patch
  - update
